.TH beret 6 "2012-03-14" "beret-1.2"
.SH NAME
beret - A 2D puzzle-platform game
.SH OPTIONS
None.
.SH DESCRIPTION
Beret is a 2D puzzle-platformer game about a scientist, astonishingly named Beret, who has gained telekinetic abilities through his research at the Evil Corporation. He decides that the Evil Corporation is a tad too evil for his liking, and begins his solitary quest to overthrow the corporation and punish the evil deeds of his employers.
.SH BUGS
If  you  encounter  any bugs in this package, please report them to the Debian Bug Tracking System at http://bugs.debian.org/.
.SH AUTHORS
beret is written by Nigel Kilmer, of kiwisauce.com. Released under the LGPL v3.

This manual page was written 2012-03-14 by Wouter Van Rooy <woutervanrooy@gmail.com> for the Debian GNU system.
